project:
  type: book
  output-dir: docs

book:
  title: "Understanding metabolic networks"
  reader-mode: true

  page-footer:
    right: |
      The Systems Virology Lab <a href="https://ki.se/en/research/research-areas-centres-and-networks/research-groups/the-systems-virology-lab-ujjwal-neogi">Link</a>.
      
  chapters:
    - index.qmd
    - part: Key Concepts
      chapters:
        - GEM.qmd
        - Context.qmd
        - FBA.qmd
    - part: Exercises
      chapters:
        - configure.qmd
        - exercises.qmd
    - references.qmd

format:
  html:
    theme:
      - united
    css: styles.css
    code-link: true

    callout-appearance: simple
editor: source